version: '3'
services:
  database:
    image: zaawansowanesystemybazdanych/bazadanych
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./setup:/opt/oracle/scripts/setup
      - ./startup:/opt/oracle/scripts/startup
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_SID=sid
      - ORACLE_PDB=pdb
      - ORACLE_PWD=pwd