version: "2"

services:
  oracle-xe:
    image: daggerok/oracle:12.1.0.2-se2
    shm_size: 1g
    environment:
      ORACLE_PWD: password
      ORACLE_SID: sid
      ORACLE_PDB: pdb
    ports:
      - "1521:1521"
    volumes:
      - ./setup:/docker-entrypoint-initdb.d/setup
      - ./startup:/docker-entrypoint-initdb.d/startup
