version: "2"

services:
  oracle-xe-custom:
    container_name: zsbd-container
    build:
      context: .
    shm_size: 1g
    environment:
      ORACLE_PWD: password
      ORACLE_SID: sid
      ORACLE_PDB: pdb
    ports:
      - "1521:1521"
    volumes:
      - ./setup:/docker-entrypoint-initdb.d/setup
      - ./startup:/docker-entrypoint-initdb.d/startup
      - ./benchmark:/home/oracle/benchmark
