CONNECT usr/pwd@//localhost:1521/pdb;

DROP TABLE PEOPLE PURGE;

CREATE TABLE PEOPLE(name VARCHAR2(10));
INSERT INTO PEOPLE (name) VALUES ('Larry');
INSERT INTO PEOPLE (name) VALUES ('Bruno');
INSERT INTO PEOPLE (name) VALUES ('Gerald');

COMMIT;
EXIT;