CREATE OR REPLACE TRIGGER REMOVE_PRODUCT
BEFORE DELETE
    ON PRODUCTS
    FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    DELETE FROM ORDER_ITEMS OI WHERE OI.PRODUCT_ID = :OLD.PRODUCT_ID;
    DELETE FROM INVENTORIES OI WHERE OI.PRODUCT_ID = :OLD.PRODUCT_ID;
    COMMIT;
END;

ALTER TABLE order_items
DROP CONSTRAINT fk_order_items_orders;

ALTER TABLE INVENTORIES
DROP CONSTRAINT fk_inventories_products;