CONNECT usr/pwd@//localhost:1521/pdb;

REM INSERTING into CUSTOMERS
SET DEFINE OFF;
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (177,'United Continental Holdings','2904 S Salina St, Syracuse, NY',5000,'http://www.unitedcontinentalholdings.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (180,'INTL FCStone','5344 Haverford Ave, Philadelphia, PA',5000,'http://www.intlfcstone.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (184,'Publix Super Markets','1795 Wu Meng, Muang Chonburi, ',1200,'http://www.publix.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (187,'ConocoPhillips','Walpurgisstr 69, Munich, ',2400,'http://www.conocophillips.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (190,'3M','Via Frenzy 6903, Roma, ',1200,'http://www.3m.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (192,'Exelon','Via Luminosa 162, Firenze, ',500,'http://www.exeloncorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (208,'Tesoro','Via Notoriosa 1942, Firenze, ',500,'http://www.tsocorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (207,'Northwestern Mutual','1831 No Wong, Peking, ',3600,'http://www.northwesternmutual.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (200,'Enterprise Products Partners','Via Notoriosa 1949, Firenze, ',2400,'http://www.enterpriseproducts.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (204,'Rite Aid','Piazza Cacchiatore 23, San Giminiano, ',3600,'http://www.riteaid.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (212,'Qualcomm','Piazza Svizzera, Milano, ',500,'http://www.qualcomm.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (216,'EMC','Via Delle Grazie 11, San Giminiano, ',700,'http://www.emc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (220,'Time Warner Cable','1597 Legend St, Mysore, Kar',3700,'http://www.twc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (223,'Northrop Grumman','1606 Sangam Blvd, New Delhi, ',5000,'http://www.northropgrumman.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (39,'Lear','2115 N Towne Ln Ne, Cedar Rapids, IA',500,'http://www.lear.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (43,'Facebook','5112 Sw 9Th St, Des Moines, IA',500,'http://www.facebook.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (46,'Supervalu','8989 N Port Washington Rd, Milwaukee, WI',500,'http://www.supervalu.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (49,'NextEra Energy','4715 Sprecher Rd, Madison, WI',600,'http://www.nexteraenergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (52,'PG&E Corp.','8600 W National Ave, Milwaukee, WI',700,'http://www.pge.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (55,'Goodyear Tire & Rubber','600 N Broadway Fl 1, Milwaukee, WI',700,'http://www.goodyear.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (59,'Micron Technology','411 E Wisconsin Ave # 2550, Milwaukee, WI',700,'http://www.micron.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (62,'ConAgra Foods','122 E Dayton St, Madison, WI',900,'http://www.conagrafoods.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (66,'Bank of New York Mellon Corp.','666 22Nd Ave Ne, Minneapolis, MN',1200,'http://www.bnymellon.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (71,'Genuine Parts','200 1St St Sw, Rochester, MN',1200,'http://www.genpt.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (75,'Omnicom Group','2134 W Genesee St, Syracuse, NY',1200,'http://www.omnicomgroup.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (79,'Monsanto','137 Lark St, Albany, NY',1200,'http://www.monsanto.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (83,'National Oilwell Varco','1 Palisade Ave Fl 2, Yonkers, NY',1200,'http://www.nov.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (86,'Marriott International','Po Box 2152, Buffalo, NY',1200,'http://www.marriott.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (228,'Kinder Morgan','1614 Gitanjali Rd, Calcutta, ',5000,'http://www.kindermorgan.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (231,'Molina Healthcare','1617 Crackers St, Bangalore - India, Kar',300,'http://www.molinahealthcare.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (235,'Lincoln National','1622 Roja St, Chennai, Tam',5000,'http://www.lfg.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (238,'C.H. Robinson Worldwide','1628 Pataudi St, New Delhi, ',1900,'http://www.chrobinson.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (242,'Synnex','1647 Suspense St, Cochin, Ker',500,'http://www.synnex.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (245,'HollyFrontier','1656 Veterans Rd, Chennai, Tam',2500,'http://www.hollyfrontier.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (249,'PBF Energy','Piazza Quattre Stagioni 4, Roma, ',3700,'http://www.pbfenergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (255,'Waste Management','Via Di Firenze 231, Roma, ',2400,'http://www.wm.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (259,'Parker-Hannifin','Canale Grande 2, Roma, ',700,'http://www.parker.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (263,'Farmers Insurance Exchange','Via Dello Croce 93, Tellaro, ',100,'http://www.farmers.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (268,'VF','1971 Limelight Blvd, Samutprakarn, ',1200,'http://www.vfc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (313,'Hertz Global Holdings','1616 Crackers Blvd, Bangalore - India, Kar',5000,'http://www.hertz.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (319,'BB&T Corp.','1668 Chong Tao, Beijing, ',200,'http://www.bbt.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (32,'Global Partners','1135 Catherine St, Ann Arbor, MI',400,'http://www.globalp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (63,'Sempra Energy','633 S Hawley Rd, Milwaukee, WI',900,'http://www.sempra.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (78,'Precision Castparts','726 Union St, Hudson, NY',1200,'http://www.precast.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (111,'W.W. Grainger','378 S Negley Ave, Pittsburgh, PA',1500,'http://www.grainger.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (125,'Air Products & Chemicals','612 Jefferson Ave, Scranton, PA',2300,'http://www.airproducts.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (163,'Charter Communications','802 North Ave, Pittsburgh, PA',3600,'http://www.charter.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (195,'Applied Materials','Via Dolorosa 69, Tellaro, ',700,'http://www.appliedmaterials.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (206,'Ally Financial','Via Notoriosa 1949, Ventimiglia, ',3600,'http://www.ally.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (218,'Lennar','1592 Silverado St, Bangalore, Kar',700,'http://www.lennar.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (243,'Hormel Foods','1648 Anamika St, Cochin, Ker',500,'http://www.hormelfoods.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (254,'PayPal Holdings','Via Dello Croce 93, Roma, ',1200,'http://www.paypal.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (266,'Autoliv','Via Delle Capeletti 52, San Giminiano, ',400,'http://www.autoliv.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (294,'Corning','Pfannenstilstr 13, Egg, ZH',2300,'http://www.corning.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (301,'Univar','1598 Legend St, Bangalore, Kar',5000,'http://www.univar.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (314,'Thrivent Financial for Lutherans','1617 Crackers St, Bangalore - India, Kar',900,'http://www.thrivent.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (88,'Walmart','1790 Grand Blvd, Schenectady, NY',1200,'http://www.walmart.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (89,'Exxon Mobil','7 Ingelside Ln, White Plains, NY',1200,'http://www.exxonmobil.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (90,'Apple','18 Glenridge Rd, Schenectady, NY',1200,'http://www.apple.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (91,'Berkshire Hathaway','6432 Rising Sun Ave, Philadelphia, PA',1200,'http://www.berkshirehathaway.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (92,'McKesson','Rr 10, Reading, PA',1200,'http://www.mckesson.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (93,'UnitedHealth Group','2455 Rose Garden Rd, Pittsburgh, PA',1200,'http://www.unitedhealthgroup.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (94,'CVS Health','1812 Timberline Rd, Altoona, PA',1200,'http://www.cvshealth.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (95,'General Motors','141 Schiller St, Reading, PA',1200,'http://www.gm.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (96,'Ford Motor','1126 Pawlings Rd, Norristown, PA',1200,'http://www.ford.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (97,'AT&T','55 Church Hill Rd, Reading, PA',1200,'http://www.att.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (98,'General Electric','354 N Prince St, Lancaster, PA',1200,'http://www.ge.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (99,'AmerisourceBergen','115 Chestnut St, Philadelphia, PA',1400,'http://www.amerisourcebergen.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (100,'Verizon','2899 Grand Ave, Pittsburgh, PA',1400,'http://www.verizon.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (101,'Chevron','Po Box 39, Indiana, PA',1400,'http://www.chevron.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (102,'Costco','1604 Broadway Ave, Pittsburgh, PA',1400,'http://www.costco.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (103,'Fannie Mae','4734 Liberty Ave, Pittsburgh, PA',1400,'http://www.fanniemae.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (104,'Kroger','21 Thornwood Rd, Harrisburg, PA',1400,'http://www.thekrogerco.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (105,'Amazon.com','3725 W Lake Rd, Erie, PA',1400,'http://www.amazon.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (106,'Walgreens Boots Alliance','1808 4Th Ave, Altoona, PA',1400,'http://www.walgreensbootsalliance.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (107,'HP','Station Sq, Pittsburgh, PA',1400,'http://www.hp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (108,'Cardinal Health','4020 Garden Ave, Erie, PA',1400,'http://www.cardinal.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (109,'Express Scripts Holding','100 N Peach St, Philadelphia, PA',1400,'http://www.express-scripts.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (110,'J.P. Morgan Chase','835 Heister Ln, Reading, PA',1400,'http://www.jpmorganchase.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (112,'Boeing','5643 N 5Th St, Philadelphia, PA',1500,'http://www.boeing.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (113,'Microsoft','1401 W Warren Rd, Bradford, PA',1500,'http://www.microsoft.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (114,'Bank of America Corp.','815 Freeport Rd, Pittsburgh, PA',1500,'http://www.bankofamerica.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (115,'Wells Fargo','327 N Washington Ave # 300, Scranton, PA',1900,'http://www.wellsfargo.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (117,'Home Depot','4901 Locust Ln, Harrisburg, PA',2300,'http://www.homedepcom');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (118,'Citigroup','3376 Perrysville Ave, Pittsburgh, PA',2300,'http://www.citigroup.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (119,'Phillips 66','220 Penn Ave # 300, Scranton, PA',2300,'http://www.phillips66.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (121,'IBM','522 Swede St, Norristown, PA',2300,'http://www.ibm.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (122,'Valero Energy','7708 City Ave, Philadelphia, PA',2300,'http://www.valero.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (123,'Anthem','1801 Lititz Pike, Lancaster, PA',2300,'http://www.antheminc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (124,'Procter & Gamble','101 E Olney Ave, Philadelphia, PA',2300,'http://www.pg.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (127,'Alphabet','36 W 34Th St, Erie, PA',2400,'http://www.google.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (128,'Comcast','1007 Mount Royal Blvd, Pittsburgh, PA',2400,'http://www.comcastcorporation.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (129,'Target','601 Market St, Philadelphia, PA',2400,'http://www.target.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (132,'MetLife','5122 Sinclair Ln, Baltimore, MD',2400,'http://www.metlife.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (133,'Archer Daniels Midland','680 Bel Air Rd, Bel Air, MD',2400,'http://www.adm.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (135,'Freddie Mac','8004 Stansbury Rd, Baltimore, MD',2400,'http://www.freddiemac.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (136,'PepsiCo','10209 Yearling Dr, Rockville, MD',2400,'http://www.pepsico.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (137,'United Technologies','3000 Greenmount Ave, Baltimore, MD',2400,'http://www.utc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (139,'Lowe?s','1262 Vocke Rd, Cumberland, MD',2400,'http://www.lowes.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (140,'UPS','3314 Eastern Ave, Baltimore, MD',2400,'http://www.ups.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (142,'Prudential Financial','11200 Scaggsville Rd, Laurel, MD',2400,'http://www.prudential.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (144,'Humana','2300 Harford Rd, Baltimore, MD',2400,'http://www.humana.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (145,'Disney','2 2Nd St # A, Ocean City, MD',2400,'http://www.disney.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (146,'Cisco Systems','6917 W Oklahoma Ave, Milwaukee, WI',2400,'http://www.cisco.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (148,'Dow Chemical','160 Glenwood Ave, Minneapolis, MN',2400,'http://www.dow.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (149,'Sysco','6915 Grand Ave, Hammond, IN',2400,'http://www.sysco.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (151,'Caterpillar','65 Cadillac Sq # 2701, Detroit, MI',2500,'http://www.caterpillar.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (152,'Lockheed Martin','3435 Tuscany Dr Se, Grand Rapids, MI',2500,'http://www.lockheedmartin.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (155,'Coca-Cola','810 1St Ave, Council Bluffs, IA',3500,'http://www.coca-colacompany.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (156,'HCA Holdings','500 W Oklahoma Ave, Milwaukee, WI',3500,'http://www.hcahealthcare.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (159,'Energy Transfer Equity','1721 E Lake St, Minneapolis, MN',3600,'http://www.energytransfer.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (160,'Tyson Foods','255 Great Arrow Ave, Buffalo, NY',3600,'http://www.tysonfoods.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (162,'Delta Air Lines','6640 Campbell Blvd, Lockport, NY',3600,'http://www.delta.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (164,'Nationwide','1136 Arch St, Philadelphia, PA',3600,'http://www.nationwide.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (166,'Best Buy','Rt 6 E, Warren, PA',3700,'http://www.bestbuy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (167,'Merck','1924 Bedford St, Cumberland, MD',3700,'http://www.merck.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (169,'Liberty Mutual Insurance Group','2713 N Bendix Dr, South Bend, IN',3700,'http://www.libertymutual.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (171,'Honeywell International','752 W Huron St, Pontiac, MI',3700,'http://www.honeywell.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (173,'Massachusetts Mutual Life Insurance','1330 N Memorial Dr, Racine, WI',5000,'http://www.massmutual.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (175,'Morgan Stanley','8 Automation Ln, Albany, NY',5000,'http://www.morganstanley.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (176,'Cigna','811 N Brandywine Ave, Schenectady, NY',5000,'http://www.cigna.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (178,'Allstate','3025 Sussex Ave, Pittsburgh, PA',5000,'http://www.allstate.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (179,'TIAA','932 High St, Lancaster, PA',5000,'http://www.tiaa.org');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (181,'CHS','6959 Tulip St, Philadelphia, PA',5000,'http://www.chsinc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (182,'American Express','511 S Central Ave # A, Baltimore, MD',5000,'http://www.americanexpress.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (183,'Gilead Sciences','400 E Joppa Rd, Baltimore, MD',5000,'http://www.gilead.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (185,'General Dynamics','1796 Tsing Tao, Muang Nonthaburi, ',1200,'http://www.generaldynamics.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (186,'TJX','1810 Tucker Crt, Mumbai, ',5000,'http://www.tjx.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (188,'Nike','Sendlinger Tor 4, Munich, ',2400,'http://www.nike.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (189,'World Fuel Services','Theresienstr 15, Munich, ',2400,'http://www.wfscorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (191,'Mondelez International','1822 Ironweed St, Toronto, ONT',1200,'http://www.mondelezinternational.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (193,'Twenty-First Century Fox','Via Notoriosa 1932 Rd, Firenze, ',500,'http://www.21cf.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (194,'Deere','Via Notoriosa 1941, Firenze, ',500,'http://www.johndeere.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (209,'Time Warner','Via Delle Grazie 11, Tellaro, ',2400,'http://www.timewarner.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (196,'DuPont','Via Notoriosa 1943, Firenze, ',2400,'http://www.dupont.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (197,'Avnet','Via Luminosa 162, Tellaro, ',700,'http://www.avnet.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (199,'Macy?s','Via Di Firenze 231, Tellaro, ',700,'http://www.macysinc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (201,'Travelers Cos.','Via Frenzy 6903, Tellaro, ',3600,'http://www.travelers.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (203,'Philip Morris International','Piazza Quattre Stagioni 4, San Giminiano, ',3600,'http://www.pmi.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (205,'Tech Data','Via Notoriosa 1932, Tellaro, ',3600,'http://www.techdata.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (211,'McDonald?s','2034 Sabrina Rd, Samutprakarn, ',3700,'http://www.aboutmcdonalds.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (213,'Sears Holdings','Ruella Delle Spiriti, Milano, ',500,'http://www.searsholdings.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (215,'Capital One Financial','Via Delle Capeletti 52, San Giminiano, ',1500,'http://www.capitalone.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (217,'USAA','Via Delli Capelli 2, San Giminiano, ',700,'http://www.usaa.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (219,'Duke Energy','1593 Silverado St, Bangalore, Kar',5000,'http://www.duke-energy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (221,'Halliburton','1602 Sholay St, Chennai, Tam',1500,'http://www.halliburton.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (224,'Arrow Electronics','1607 Sangam Blvd, New Delhi, ',5000,'http://www.arrow.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (1,'Raytheon','514 W Superior St, Kokomo, IN',100,'http://www.raytheon.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (2,'Plains GP Holdings','2515 Bloyd Ave, Indianapolis, IN',100,'http://www.plainsallamerican.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (3,'US Foods Holding','8768 N State Rd 37, Bloomington, IN',100,'http://www.usfoods.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (4,'AbbVie','6445 Bay Harbor Ln, Indianapolis, IN',100,'http://www.abbvie.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (5,'Centene','4019 W 3Rd St, Bloomington, IN',100,'http://www.centene.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (6,'Community Health Systems','1608 Portage Ave, South Bend, IN',100,'http://www.chs.net');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (7,'Alcoa','23943 Us Highway 33, Elkhart, IN',100,'http://www.alcoa.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (8,'International Paper','136 E Market St # 800, Indianapolis, IN',100,'http://www.internationalpaper.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (9,'Emerson Electric','1905 College St, South Bend, IN',100,'http://www.emerson.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (10,'Union Pacific','3512 Rockville Rd # 137C, Indianapolis, IN',200,'http://www.up.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (11,'Amgen','1303 E University St, Bloomington, IN',200,'http://www.amgen.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (12,'U.S. Bancorp','115 N Weinbach Ave, Evansville, IN',200,'http://www.usbank.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (13,'Staples','2067 Rollett Ln, Evansville, IN',200,'http://www.staples.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (14,'Danaher','1105 E Allendale Dr, Bloomington, IN',200,'http://www.danaher.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (15,'Whirlpool','18305 Van Dyke St, Detroit, MI',200,'http://www.whirlpoolcorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (16,'Aflac','Lucas Dr Bldg 348, Detroit, MI',200,'http://www.aflac.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (17,'AutoNation','1801 Monroe Ave Nw, Grand Rapids, MI',200,'http://www.autonation.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (18,'Progressive','4925 Kendrick St Se, Grand Rapids, MI',200,'http://www.progressive.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (19,'Abbott Laboratories','3310 Dixie Ct, Saginaw, MI',200,'http://www.abbott.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (20,'Dollar General','113 Washington Sq N, Lansing, MI',200,'http://www.dollargeneral.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (21,'Tenet Healthcare','2500 S Pennsylvania Ave, Lansing, MI',200,'http://www.tenethealth.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (22,'Eli Lilly','3213 S Cedar St, Lansing, MI',200,'http://www.lilly.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (24,'Southwest Airlines','6654 W Lafayette St, Detroit, MI',200,'http://www.southwest.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (25,'Penske Automotive Group','27 Benton Rd, Saginaw, MI',200,'http://www.penskeautomotive.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (26,'ManpowerGroup','8201 Livernois Ave, Detroit, MI',300,'http://www.manpowergroup.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (28,'Kohl?s','3100 E Eisenhower Pky # 100, Ann Arbor, MI',300,'http://www.kohlscorporation.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (29,'Starbucks','952 Vassar Dr, Kalamazoo, MI',400,'http://www.starbucks.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (30,'Paccar','150 W Jefferson Ave # 2500, Detroit, MI',400,'http://www.paccar.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (31,'Cummins','40 Pearl St Nw # 1020, Grand Rapids, MI',400,'http://www.cummins.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (33,'Altria Group','301 E Genesee Ave, Saginaw, MI',400,'http://www.altria.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (34,'Xerox','9936 Dexter Ave, Detroit, MI',400,'http://www.xerox.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (35,'Kimberly-Clark','1660 University Ter, Ann Arbor, MI',400,'http://www.kimberly-clark.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (36,'Hartford Financial Services Group','15713 N East St, Lansing, MI',400,'http://www.thehartford.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (38,'Kraft Heinz','10315 Hickman Rd, Des Moines, IA',500,'http://www.kraftheinzcompany.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (40,'Fluor','1928 Sherwood Dr, Council Bluffs, IA',500,'http://www.fluor.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (41,'AECOM','2102 E Kimberly Rd, Davenport, IA',500,'http://www.aecom.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (44,'Jabil Circuit','221 3Rd Ave Se # 300, Cedar Rapids, IA',500,'http://www.jabil.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (45,'CenturyLink','2120 Heights Dr, Eau Claire, WI',500,'http://www.centurylink.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (47,'General Mills','6555 W Good Hope Rd, Milwaukee, WI',600,'http://www.generalmills.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (48,'Southern','1314 N Stoughton Rd, Madison, WI',600,'http://www.southerncompany.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (50,'Thermo Fisher Scientific','6161 N 64Th St, Milwaukee, WI',700,'http://www.thermofisher.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (51,'American Electric Power','11016 W Lincoln Ave, Milwaukee, WI',700,'http://www.aep.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (53,'NGL Energy Partners','615 N Sherman Ave, Madison, WI',700,'http://www.nglenergypartners.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (54,'Bristol-Myers Squibb','512 E Grand Ave, Beloit, WI',700,'http://www.bms.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (56,'Nucor','5235 N Ironwood Ln, Milwaukee, WI',700,'http://www.nucor.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (57,'PNC Financial Services Group','322 E Michigan St, Milwaukee, WI',700,'http://www.pnc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (58,'Health Net','1400 Bellinger St Fl 4, Eau Claire, WI',700,'http://www.healthnet.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (60,'Colgate-Palmolive','808 3Rd St # 100, Wausau, WI',700,'http://www.colgatepalmolive.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (61,'Freeport-McMoRan','300 Crooks St, Green Bay, WI',900,'http://www.fcx.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (64,'Gap','2122 Campbell Rd, La Crosse, WI',1200,'http://www.gapinc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (65,'Baker Hughes','3324 N Oakland Ave, Milwaukee, WI',1200,'http://www.bakerhughes.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (67,'Dollar Tree','1501 Lowry Ave N, Minneapolis, MN',1200,'http://www.dollartree.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (69,'Whole Foods Market','4200 Yosemite Ave S, Minneapolis, MN',1200,'http://www.wholefoodsmarket.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (70,'PPG Industries','2800 Chicago Ave # 100, Minneapolis, MN',1200,'http://www.ppg.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (72,'Icahn Enterprises','314 W Superior St # 1015, Duluth, MN',1200,'http://www.ielp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (74,'Performance Food Group','2720 Brewerton Rd, Syracuse, NY',1200,'http://www.pfgc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (76,'DISH Network','1522 Main St, Niagara Falls, NY',1200,'http://www.dish.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (77,'FirstEnergy','49 N Pine Ave, Albany, NY',1200,'http://www.firstenergycorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (80,'AES','33 Fulton St, Poughkeepsie, NY',1200,'http://www.aes.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (81,'CarMax','2360 Maxon Rd, Schenectady, NY',1200,'http://www.carmax.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (84,'NRG Energy','500 S Salina St # 500, Syracuse, NY',1200,'http://www.nrgenergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (85,'Western Digital','33 Pine St, Lockport, NY',1200,'http://www.westerndigital.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (226,'Office Depot','1612 Talaivar St, Chennai, Tam',5000,'http://www.officedepcom');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (227,'Nordstrom','1613 Victoria St, Calcutta, ',5000,'http://www.nordstrom.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (229,'Aramark','1615 Crackers Crt, Chennai - India, ',300,'http://www.aramark.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (230,'DaVita HealthCare Partners','1616 Mr. India Ln, Bombay - India, Kar',300,'http://www.davita.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (232,'WellCare Health Plans','1618 Villains St, New Delhi - India, ',1200,'http://www.wellcare.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (233,'CBS','1619 Bowlers Rd, Chandigarh, Har',1200,'http://www.cbscorporation.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (234,'Visa','1620 Sixers Crt, Bombay, Kar',5000,'http://www.visa.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (236,'Ecolab','1623 Hey Ram St, Chennai - India, ',5000,'http://www.ecolab.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (237,'Kellogg','1627 Sowdagar St, New Delhi, ',1900,'http://www.kelloggcompany.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (239,'Textron','1632 Splash St, Chandigarh, Har',2500,'http://www.textron.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (240,'Loews','1636 Pretty Blvd, Bangalore, Kar',5000,'http://www.loews.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (241,'Illinois Tool Works','1646 Brazil Blvd, Chennai, Tam',500,'http://www.itw.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (244,'Viacom','1650 Teesri Manjil Crt, Kashmir, ',3700,'http://www.viacom.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (246,'Land O?Lakes','1662 Talaivar St, Chennai, Tam',1500,'http://www.landolakesinc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (248,'Devon Energy','Piazza Del Congresso 22, Roma, ',3700,'http://www.devonenergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (251,'Yum Brands','Ruella Delle Spiriti, Roma, ',500,'http://www.yum.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (252,'Texas Instruments','Via Del Disegno 194, Roma, ',500,'http://www.ti.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (253,'CDW','Via Delle Capeletti 52, Roma, ',500,'http://www.cdw.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (256,'Marsh & McLennan','Via Dolorosa 69, Roma, ',2400,'http://www.mmc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (257,'Chesapeake Energy','Via Notoriosa 1942, Ventimiglia, ',700,'http://www.chk.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (260,'Occidental Petroleum','Piazza Cacchiatore 23, Roma, ',700,'http://www.oxy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (261,'Guardian Life Ins. Co. of America','Via Del Disegno 194, San Giminiano, ',600,'http://www.guardianlife.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (264,'J.C. Penney','Via Dello Croce 93, San Giminiano, ',400,'http://www.jcpenney.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (265,'Consolidated Edison','Ruella Delle Spiriti, San Giminiano, ',400,'http://www.conedison.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (267,'Cognizant Technology Solutions','Via Delli Capelli 2, Tellaro, ',400,'http://www.cognizant.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (269,'Ameriprise Financial','Harmoniegasse 3, Baden-Daettwil, AG',500,'http://www.ameriprise.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (271,'Computer Sciences','Alfred E. Neumann-Weg 3, Baden-Daettwil, AG',500,'http://www.csc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (272,'L Brands','Dr. Herbert Bitto Str 23, Baden-Daettwil, AG',2300,'http://www.lb.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (273,'Jacobs Engineering Group','Taefernstr 4, Baden-Daettwil, AG',2300,'http://www.jacobs.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (275,'Principal Financial','Helebardenweg 5, Baden-Daettwil, AG',3500,'http://www.principal.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (276,'Ross Stores','Zum Freundlichen Nachbarn 5, Baden-Daettwil, AG',3500,'http://www.rossstores.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (277,'Bed Bath & Beyond','Ziegenwiese 3, Baden-Daettwil, AG',3500,'http://www.bedbathandbeyond.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (278,'CSX','Am Waldrand 5, Baden-Daettwil, AG',3500,'http://www.csx.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (279,'Toys ?R? Us','Zur Kantine 9, Baden-Daettwil, AG',1200,'http://www.toysrusinc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (280,'Las Vegas Sands','Grosse Bahnhostrasse 3, Baden-Daettwil, AG',1200,'http://www.sands.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (281,'Leucadia National','Paradeplatz 4, Zuerich, ZH',1200,'http://www.leucadia.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (282,'Dominion Resources','Badenerstr 1941, Zuerich, ZH',3500,'http://www.dom.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (283,'United States Steel','Welschdoerfchen 1941, Chur, ZH',3500,'http://www.ussteel.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (284,'L-3 Communications','Le Reduit, Tschiertschen, GR',1400,'http://www.l-3com.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (285,'Edison International','Bendlehn, Trogen, SG',1400,'http://www.edisoninvestor.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (286,'Entergy','Spisertor 3, St. Gallen, SG',1400,'http://www.entergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (287,'ADP','Langstr 14, Zuerich, ZH',700,'http://www.adp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (288,'First Data','Roessligasse 4, Zurich, ZH',700,'http://www.firstdata.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (289,'BlackRock','Zum Froehlichen Schweizer 3, Zurich, ZH',5000,'http://www.blackrock.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (290,'WestRock','Chrottenweg, Bern, BE',5000,'http://www.westrock.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (291,'Voya Financial','Bruppacher Str 3, Baden-Daettwil, AG',5000,'http://www.voya.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (292,'Sherwin-Williams','Limmatquai, Zuerich, ZH',1800,'http://www.sherwin.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (293,'Hilton Worldwide Holdings','Dreikoenigsstr 3, Zurich, ZH',1800,'http://www.hiltonworldwide.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (295,'R.R. Donnelley & Sons','Kreuzstr 32, Zurich, ZH',2300,'http://www.rrdonnelley.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (296,'Stanley Black & Decker','1539 Stripes Rd, Baden-Daettwil, AG',2300,'http://www.stanleyblackanddecker.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (299,'Murphy USA','1593 Silverado St, Bangalore, Kar',1400,'http://corporate.murphyusa.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (300,'CBRE Group','1596 Commando Blvd, Bangalore, Kar',1200,'http://www.cbre.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (302,'D.R. Horton','1599 Legend Rd, Bangalore, Kar',5000,'http://www.drhorton.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (303,'Estee Lauder','1600 Target Crt, Bangalore, Kar',5000,'http://www.elcompanies.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (304,'Praxair','1603 Rebel St, Bangalore, Kar',500,'http://www.praxair.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (305,'Biogen','1604 Volunteers Rd, Bangalore, Kar',500,'http://www.biogen.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (307,'State Street Corp.','1607 Abwdrts St, Bangalore, Kar',3500,'http://www.statestreet.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (308,'Unum Group','1608 Amadeus St, Bangalore, Kar',3500,'http://www.unum.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (309,'Reynolds American','1610 Betrayal Crt, Bangalore, Kar',5000,'http://www.reynoldsamerican.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (311,'Group 1 Automotive','1614 Crackers Rd, Bangalore - India, Kar',2300,'http://www.group1auto.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (312,'Henry Schein','1615 Crackers Crt, Bangalore - India, Kar',5000,'http://www.henryschein.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (315,'Norfolk Southern','1618 Footloose St, Bangalore - India, Kar',900,'http://www.nscorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (316,'Reinsurance Group of America','1619 Footloose Rd, Bangalore - India, Kar',900,'http://www.rgare.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (317,'Public Service Enterprise Group','1621 Gargon! Blvd, Bangalore - India, Kar',600,'http://www.pseg.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (23,'DTE Energy','8110 Jackson Rd, Ann Arbor, MI',200,'http://www.dteenergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (27,'Assurant','101 N Falahee Rd, Jackson, MI',300,'http://www.assurant.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (37,'Huntsman','555 John F Kennedy Rd, Dubuque, IA',500,'http://www.huntsman.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (42,'Becton Dickinson','1691 Asbury Rd, Dubuque, IA',500,'http://www.bd.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (68,'AutoZone','113 N 1St St, Minneapolis, MN',1200,'http://www.autozone.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (73,'Navistar International','1409 Willow St # 600, Minneapolis, MN',1200,'http://www.navistar.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (82,'Discover Financial Services','85 High St, Buffalo, NY',1200,'http://www.discoverfinancial.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (87,'Liberty Interactive','2979 Hamburg St, Schenectady, NY',1200,'http://www.libertyinteractive.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (116,'Baxter International','810 Race St, Philadelphia, PA',1900,'http://www.baxter.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (120,'Stryker','135 S 18Th St # 1, Philadelphia, PA',2300,'http://www.stryker.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (130,'Western Refining','5565 Baynton St, Philadelphia, PA',2400,'http://www.wnr.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (154,'Universal Health Services','1751 Madison Ave, Council Bluffs, IA',3500,'http://www.uhsinc.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (158,'Owens & Minor','310 Broadway St, Alexandria, MN',3600,'http://www.owens-minor.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (168,'Advance Auto Parts','2674 Collingwood St, Detroit, MI',3700,'http://www.advanceautoparts.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (172,'MasterCard','660 Woodward Ave # 2290, Detroit, MI',3700,'http://www.mastercard.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (198,'Eastman Chemical','2017 Convoy St, Tokyo, ',2400,'http://www.eastman.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (202,'Sonic Automotive','Piazza Del Congresso 22, San Giminiano, ',3600,'http://www.sonicautomotive.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (210,'CST Brands','2033 Spartacus St, Samutprakarn, ',3700,'http://www.cstbrands.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (214,'eBay','Via Del Disegno 194, Milano, ',1500,'http://www.ebay.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (222,'GameStop','1605 Bazigar Crt, Pune, ',5000,'http://www.gamestopcorp.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (225,'Reliance Steel & Aluminum','1609 Pakija Rd, New Delhi, ',3700,'http://www.rsac.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (247,'Celgene','1667 2010 St, Batavia, Ker',500,'http://www.celgene.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (250,'Genworth Financial','Piazza Svizzera, Roma, ',2400,'http://www.genworth.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (258,'Priceline Group','Via Notoriosa 1943, Ventimiglia, ',700,'http://www.pricelinegroup.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (262,'MGM Resorts International','Piazza Svizzera, San Giminiano, ',100,'http://www.mgmresorts.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (270,'Fidelity National Financial','Sonnenberg 4, Baden-Daettwil, AG',500,'http://www.fnf.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (274,'Republic Services','Kreuzritterplatz 5, Baden-Daettwil, AG',3500,'http://www.republicservices.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (298,'Peter Kiewit Sons?','1592 Silverado St, Bangalore, Kar',1400,'http://www.kiewit.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (306,'Mosaic','1606 Volunteers Blvd, Bangalore, Kar',3500,'http://www.mosaicco.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (310,'Core-Mark Holding','1611 Carmen Blvd, Bangalore, Kar',5000,'http://www.core-mark.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (318,'Cameron International','1667 2010 St, Batavia, IL',200,'http://www.c-a-m.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (297,'Xcel Energy','1540 Stripes Crt, Baden-Daettwil, AG',400,'http://www.xcelenergy.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (126,'State Farm Insurance Cos.','223 4Th Ave # 1100, Pittsburgh, PA',2300,'http://www.statefarm.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (131,'Johnson & Johnson','5640 Fishers Ln, Rockville, MD',2400,'http://www.jnj.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (134,'Marathon Petroleum','4301 Ashland Ave, Baltimore, MD',2400,'http://www.marathonpetroleum.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (138,'Aetna','200 E Fort Ave, Baltimore, MD',2400,'http://www.aetna.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (141,'AIG','12817 Coastal Hwy, Ocean City, MD',2400,'http://www.aig.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (143,'Intel','9435 Washington Blvd N # M, Laurel, MD',2400,'http://www.intel.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (147,'Pfizer','206 S Broadway # 707, Rochester, MN',2400,'http://www.pfizer.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (150,'FedEx','2215 Oak Industrial Dr Ne, Grand Rapids, MI',2400,'http://www.fedex.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (153,'New York Life Insurance','215 4Th Ave Se, Cedar Rapids, IA',2500,'http://www.newyorklife.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (157,'Ingram Micro','4811 S 76Th St # 205, Milwaukee, WI',3600,'http://www.ingrammicro.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (161,'American Airlines Group','800 Carter St, Rochester, NY',3600,'http://www.aa.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (165,'Johnson Controls','6Th And Master St, Philadelphia, PA',3600,'http://www.johnsoncontrols.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (170,'Goldman Sachs Group','23985 Bedford Rd N, Battle Creek, MI',3700,'http://www.gs.com');
Insert into CUSTOMERS (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (174,'Oracle','701 Seneca St, Buffalo, NY',5000,'http://www.oracle.com');

COMMIT;