CREATE OR REPLACE PROCEDURE END_OF_DAY_STOCK_UPDATE AS
    CURSOR productsCursor IS SELECT * FROM INVENTORIES WHERE QUANTITY<100;
BEGIN
    for product in productsCursor loop
        UPDATE INVENTORIES
        SET QUANTITY = QUANTITY+100
        WHERE PRODUCT_ID=product.PRODUCT_ID AND WAREHOUSE_ID=product.WAREHOUSE_ID;
        end loop;
END;

BEGIN DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME => 'STOCK_UPDATE_AT_23',
    JOB_ACTION => 'END_OF_DAY_STOCK_UPDATE();',
    JOB_TYPE => 'PLSQL_BLOCK',
    REPEAT_INTERVAL => 'FREQ=DAILY;BYHOUR=23',
    ENABLED => true,
    START_DATE => SYSTIMESTAMP
    );
END;

