ALTER SESSION SET CONTAINER=pdb;
CREATE USER usr IDENTIFIED BY pwd;
GRANT CONNECT, RESOURCE TO usr;
ALTER USER usr QUOTA UNLIMITED ON USERS;
CREATE DIRECTORY dpdir AS '/home/oracle/benchmark';
GRANT READ, WRITE ON DIRECTORY dpdir to usr;

EXIT;